### ISSUE TITLE
murmur don't include the license file

### ISSUE THREAD

**Issue by puntogil** [sangupta/murmur#1]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by puntogil** [comment]
Sorry for the noise

**Comment by puntogil** [comment]
license file should be http://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by sangupta** [comment]
Added license file.
